services:
  redis:
    image: redis:latest
    container_name: redisdb
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - IP_RATE_LIMIT=5
      - TOKEN_RATE_LIMIT=100
      - BLOCK_DURATION=300
    depends_on:
      - redis
